parameters:
    sil.model.manufacturing_bom_line.class:    Sil\Bundle\ManufacturingBundle\Domain\Entity\BomLine
    sil.model.manufacturing_bom.class:         Sil\Bundle\ManufacturingBundle\Domain\Entity\Bom
