parameters:
    sil_manufacturing.entity.bom_line.class:    Sil\Bundle\ManufacturingBundle\Domain\Entity\BomLine
    sil_manufacturing.entity.bom.class:         Sil\Bundle\ManufacturingBundle\Domain\Entity\Bom
