
services:
    sil_manufacturing.admin.bom_line:
        class: Sil\Bundle\ManufacturingBundle\Admin\BomLineAdmin
        arguments: [~, Sil\Bundle\ManufacturingBundle\Domain\Entity\BomLine, BlastCoreBundle:CRUD]
        calls:
            - ["setResourceRepository", ['@sil.manufacturing.repository.bom_line']]
            - [ setTemplates, [{show: SilStockBundle:CRUD:show.html.twig,edit: SilStockBundle:CRUD:edit.html.twig,list: SilStockBundle:CRUD:list.html.twig}]]

        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Manufacturing
                label: sil.manufacturing.bom_line
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
